package node;

public enum Attribute {
    HREF,STYLE,CLASS,ID,REL,TYPE,SRC,
    AUTOCOMPLETE,CHARSET,CHECKED,CONTENT,
    DIRNAME,ENCTYPE,FORM,HEIGHT,HIDDEN,LABEL,HTTP_EQUIV,MEDIA,NOVALIDATE,
    ONCHANGE,ONCLICK,ONDRAGEND,ONDRAGOVER,ONDRAGSTART,ONDRAGENTER,ONDRAGLEAVE,
    ONDROP,ONFOCUS,ONINVALID,ONKEYDOWN,ONKEYPRESS,ONLOAD,ONMOUSEMOVE,ONMOUSEOUT,ONMOUSEOVER,
    ONMOUSEUP,ONMOUSEWHEEL,PLACEHOLDER,ROWS,ROWSPAN,SELECTED,SPAN,TITLE,ALT,VALUE,WIDTH;

    @Override
    public String toString() {
        return super.toString().toLowerCase();
    }
}
